### ISSUE TITLE
Camera is Freezing

### ISSUE THREAD

**Issue by enversalih** [Glamdring/EasyCamera#2]
After i open easycamera class, i get preview of the camera but camera is freezing.

public class MakePhotoActivity extends Activity {

	SurfaceHolder previewHolder;
	SurfaceView mSurfaceView;
	private boolean previewIsRunning;
	private EasyCamera camera;
	 
	@Override
	public void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		setContentView(R.layout.activity_main);

		mSurfaceView = (SurfaceView) findViewById(R.id.surface);
		previewHolder = mSurfaceView.getHolder();
		previewHolder.addCallback(new SurfaceHolder.Callback() {

            public void surfaceChanged(SurfaceHolder holder, int format,
                    int width, int height) {
            	 if (!previewIsRunning && (camera != null)) {
                     try {
						camera.startPreview(holder);
					} catch (IOException e) {
						// TODO Auto-generated catch block
						e.printStackTrace();
					}
                     previewIsRunning = true;
                 }
            }

            public void surfaceCreated(SurfaceHolder holder) {

        		camera = DefaultEasyCamera.open(CameraInfo.CAMERA_FACING_FRONT);

            }

            public void surfaceDestroyed(SurfaceHolder holder) { 
            	camera.close();
                camera = null;

            }

        });
	}

}

**Comment by Glamdring** [comment]
Hi, can you elaborate please? Did you manage to resolve to problem?

**Comment by Glamdring** [comment]
I'm closing the issue due to lack of more details. Feel free to reopen it when you are available.
