### ISSUE TITLE
Gradle

### ISSUE THREAD

**Issue by theGlenn** [Glamdring/EasyCamera#4]
Everything is in the title building this lib as a Gradle dependency  could be a great fit to help everybody with android camera nightmare :+1:

**Comment by Glamdring** [comment]
Doesn't it work out of the box? E.g. 
compile 'net.bozho.easycamera:easycamera:0.0.1'

**Comment by theGlenn** [comment]
Nope you need to build as a gradle dependencies and make it avalaible on jcenter

**Comment by Glamdring** [comment]
It uses a classifier - how do you add a classifier in gradle?

**Comment by Glamdring** [comment]
Will check

**Comment by Glamdring** [comment]
Aha, Maven makes a difference between "classifier" and "type". Could you try something like the thing shown here: http://stackoverflow.com/questions/16682847/how-to-manually-include-external-aar-package-using-new-gradle-android-build-syst e.g. using: ext: "aar" (if it doesn't work, try adding classifier as well)

**Comment by theGlenn** [comment]
Ok I tried this `compile 'net.bozho.easycamera:easycamera:0.0.1:aar@aar'` and it works. 
You should add it to you README.md :+1:

**Comment by Glamdring** [comment]
Done, added to readme. Thanks.
