### ISSUE TITLE
Black Screen

### ISSUE THREAD

**Issue by rafaelcorreiapoli** [Glamdring/EasyCamera#6]
Hello! when I call startPreview on the onCreate method of an activity or a fragment, the surface becomes black (but my webcam turns on the led indicating it's on)
it only works when i call startPreview on a click of a button or something that will happen on a later time..
How can I fix that?

**Comment by PriteshJain** [comment]
May I know what device and android version?

**Comment by rafaelcorreiapoli** [comment]
API 22

**Comment by ericwan78** [comment]
@rafaelcorreiapoli I had the same problem. The issue is your code calling  startPreview before the surface is ready. Trying add callback to your surface and call startPreview in the onSurfaceChanged method.
