### ISSUE TITLE
Camera Example

### ISSUE THREAD

**Issue by uxmanz** [Glamdring/EasyCamera#8]
hi there, can you please make an example for your _looks like awesome_ api please.

sincerely,
A guy that can't get it to work.

**Comment by Glamdring** [comment]
Hello,

There's a short example in the readme. Which part in particular isn't working for you? And on what android version?

**Comment by idan6189** [comment]
hello,
To be honest i can find an example of what SurfaceView I should add in the xml?

**Comment by Glamdring** [comment]
One example https://github.com/josnidhin/Android-Camera-Example/blob/master/res/layout/main.xml
I also updated the readme to include a sample way to obtain the view
